### ISSUE TITLE
[Light Client] Add language field for events

### ISSUE THREAD

**Issue by dwalintukan** [bodhiproject/bodhi-server#11]
Need a `language` field for Topics/Oracles so they can be filtered on the frontend.

**Comment by henryzbw** [comment]
@dwalintukan for this issue, do we need to add the field to smart contract? since i'm still confused when we create an event if the language information is not pushed on chain, how can other persons get the language of this event.

**Comment by dwalintukan** [comment]
@henryzbw Don't need to alter the smart contract. When we do a mutation it will include a language field. The UI does two calls, one for Qrypto and one to the server (mutation).
