### ISSUE TITLE
when in full-screen, make a bet, when click confirm, the qrypto confirm window will be a new tab in chrome

### ISSUE THREAD

**Issue by henryzbw** [bodhiproject/bodhi-server#131]
![image](https://user-images.githubusercontent.com/10339131/46562313-5de6b480-c8b0-11e8-8fa2-90309bc7ef76.png)

don't know if its good or bad

**Comment by dwalintukan** [comment]
This should be an issue in the Qrypto repo. 
https://github.com/bodhiproject/qrypto/issues/190
