### ISSUE TITLE
votes.db migration

### ISSUE THREAD

**Issue by BernardHan** [bodhiproject/bodhi-server#144]
add a `type` field in `votes.db`: [VOTE, RESULT_SET, BET]

@dwalintukan 
By adding this field, I think we can just pull resultsetting history from `votes.db` not `resultsets.db`, since then we can tell if it's a result set and it has `amount`. There's no need to migrate `resultsets.db` anymore.

Implementation:
1. go through all `votes`
2. if the entry uses `QTUM`, then it's a `BET`
3. if it uses `BOT`, then query the Oracle
4. if Oracle == Centralized, then it's a `RESULT_SET`, otherwise it's a `VOTE`

**Comment by BernardHan** [comment]
Or maybe I don't even need to do migration?

Like how you added `block`:

``` js
  Vote: {
    block: async ({ blockNum }, data, { db: { Blocks } }) => (await Blocks.find({ blockNum }))[0],
    type:  async ({ token, oracleAddress }, { db: { Oracles } }) => {
        if (token === 'QTUM') return 'BET';
        const oracle = await Oracles.find({ oracleAddress });
        if (oracle.token === 'QTUM') return 'RESULT_SET';
        return 'VOTE';
    },
  },
```

**Comment by dwalintukan** [comment]
@BernardHan this could work by adding a resolver. But at the cost of increased query time. I think the migration makes more sense long term to have it as part of the table.

**Comment by BernardHan** [comment]
@dwalintukan I'll finish the migration tomorrow.

**Comment by dwalintukan** [comment]
Sounds good.
