### ISSUE TITLE
Make event status more explicit

### ISSUE THREAD

**Issue by henryzbw** [bodhiproject/bodhi-server#233]
CREATED -> PRE_BETTING -> BETTING -> PRE_RESULT_SETTING -> ORACLE-RESULT_SETTING -> OPEN-RESULT_SETTING -> ARBITRATION -> WITHDRAW

**Comment by dwalintukan** [comment]
Only adding PRE_BETTING

**Comment by henryzbw** [comment]
@dwalintukan TT wants to add PRE_RESULT_SETTING now

**Comment by dwalintukan** [comment]
@henryzbw ok

**Comment by dwalintukan** [comment]
#235 #236
