### ISSUE TITLE
change port 5555 to 8773 (or others)

### ISSUE THREAD

**Issue by amazingandyyy** [bodhiproject/bodhi-server#35]
current port - `5555` is too general. port 3000, 4000, 5000, 5555, 8000, 8888 are generally used by other projects.

we can consider to use other port

examples are some other blockchain projects, for example `:8545` for [geth](https://github.com/ethereum/go-ethereum), `:8669` for [thor](https://github.com/vechain/thor)

we can consider to use others port for example `:8773`.

**Comment by amazingandyyy** [comment]
refer to https://github.com/bodhiproject/website/issues/280

**Comment by dwalintukan** [comment]
let me look into some port numbers we can use

**Comment by dwalintukan** [comment]
8877 looks unused
https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers

**Comment by dwalintukan** [comment]
lets change this in the near future though. it requires changing stuff on different repos.

**Comment by amazingandyyy** [comment]
yea, it will relate to many different repos and documentations.

**Comment by amazingandyyy** [comment]
8877 has a bad meaning in Taiwanese,  and 7788 has a bad meaning in mandarin haha

**Comment by amazingandyyy** [comment]
just create [one prediciton](http://localhost:3000/oracle/f4e494326c2be9ac5c08c18174acc91e04baf2c4/ab76450770afaf6ef7e5dba156c28af2d2117b9a/deb44301e9e658d99ed8849568d240d28d3a1fbb0fa62f009513f418602a7971) for fun you if you have the -ui running

**Comment by amazingandyyy** [comment]
Today when Henry asked me to vote while I am fixing the website repo which is also on 5555, I need to either shut down my python VM or change 5555 to 5554 >.<

**Comment by dwalintukan** [comment]
@amazingandyyy Let's do 8989. It's easy enough to remember.

**Comment by dwalintukan** [comment]
#40
