### ISSUE TITLE
Default qtum folder always set to Mac

### ISSUE THREAD

**Issue by ippudo** [bodhiproject/bodhi-server#57]
Happens at both Linux and Windows.

It works if putting qtum bins under Mac folder.

**Comment by dwalintukan** [comment]
@ippudo can you explain this bug? are you talking about the dev env is using mac only? if so that is set as default in the npm scripts (package.json). this is cause everyone is using a mac.

are you using windows/linux?

**Comment by ippudo** [comment]
Um yeah sorry I didn't check the script. I'm using windows/linux.

**Comment by dwalintukan** [comment]
no problem. that makes a good point. lets add more scripts for different environments.

**Comment by amazingandyyy** [comment]
@ippudo  do you know how to fix it?
